### ISSUE TITLE
gulp watch - libsass error

### ISSUE THREAD

**Issue by wsergio** [jumph-io/Jumph#22]
Hey,
I came across this error while setting up Jumph.

```
$ gulp watch
[15:55:03] Warning: gulp version mismatch:
[15:55:03] Global gulp is 3.9.1
[15:55:03] Local gulp is 3.8.11
D:\web\www\Jumph\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (D:\web\www\Jumph\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (D:\web\www\Jumph\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\web\www\Jumph\node_modules\gulp-sass\index.js:3:17)
```

**Comment by wsergio** [comment]
I was able to get rid of that using:
```
npm uninstall --save-dev gulp-sass
npm install --save-dev gulp-sass@2
```
Maybe it helps others too.
Cheers.
